# Generated by Django 5.1.3 on 2024-11-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petregistration',
            name='emirates_id',
            field=models.CharField(max_length=250),
        ),
    ]
