# Generated by Django 5.1.3 on 2024-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_petregistration_emirates_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='petregistration',
            name='competitions',
            field=models.ManyToManyField(blank=True, to='core.competition'),
        ),
    ]
