# Generated by Django 5.1.3 on 2024-11-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_petregistration_competitions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petregistration',
            name='competition',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Competion1', 'Competion1'), ('Competion2', 'Competion2')], max_length=250, null=True),
        ),
    ]
