# Generated by Django 5.1.3 on 2024-11-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_petregistration_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petregistration',
            name='competition',
            field=models.CharField(blank=True, choices=[('Competion1', 'Competion1'), ('Competion2', 'Competion2')], max_length=250, null=True),
        ),
    ]
