# Generated by Django 5.1.3 on 2024-11-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_petregistration_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petregistration',
            name='competition',
            field=models.CharField(blank=True, choices=[('Competition1', 'Competition1'), ('Competition2', 'Competition2')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='petregistration',
            name='pet_photo',
            field=models.FileField(blank=True, null=True, upload_to='Pet Registration'),
        ),
    ]
