# Generated by Django 5.1.3 on 2024-11-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_petregistration_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petregistration',
            name='instagram',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
