# Generated by Django 5.1.3 on 2024-11-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_petregistration_instagram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petregistration',
            old_name='pet_photo_competition',
            new_name='pet_talent_show',
        ),
        migrations.RenameField(
            model_name='petregistration',
            old_name='pet_trick_competition',
            new_name='snap_my_pet',
        ),
    ]
