# Generated by Django 5.1.3 on 2024-12-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_pet_photo_competition_petregistration_pet_talent_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='have_pets',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=255),
            preserve_default=False,
        ),
    ]
