# Generated by Django 5.1.3 on 2024-12-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tickets_have_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_name', models.CharField(max_length=255)),
                ('friend_name', models.CharField(max_length=255)),
                ('friend_email', models.EmailField(max_length=254)),
                ('friend_mobile', models.CharField(max_length=15)),
                ('friend_nationality', models.CharField(max_length=100)),
                ('how_many_members', models.PositiveIntegerField()),
                ('have_pets', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
