# Generated by Django 5.1.3 on 2024-12-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='have_pets',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
