# Generated by Django 5.1.3 on 2024-12-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_referral_have_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='friend_mobile',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='friend_nationality',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='have_pets',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='how_many_members',
        ),
        migrations.AddField(
            model_name='referral',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='friend_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='friend_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
