# Generated by Django 5.1.3 on 2024-12-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_referral_friend_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referrer_name',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='friend_email',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='friend_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='slug',
        ),
        migrations.AddField(
            model_name='referral',
            name='have_pets',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='how_many_members',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='mobile',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='nationality',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
