# Generated by Django 5.1.3 on 2024-12-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_referrer_name_referral_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
