# Generated by Django 5.1.3 on 2024-12-05 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_referral_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='how_many_members',
        ),
        migrations.AddField(
            model_name='petregistration',
            name='referrals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.referral'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='referrals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.referral'),
        ),
    ]
