# Generated by Django 5.1.3 on 2024-12-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_referral_how_many_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='referrals',
        ),
        migrations.AddField(
            model_name='tickets',
            name='referral_slug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.referral'),
        ),
    ]
