# Generated by Django 5.1.3 on 2024-12-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_tickets_referrals_tickets_referral_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='referral_slug',
            new_name='referral',
        ),
    ]
